# @format

name: example_flutter
description: A new Flutter project.
publish_to: "none"
version: 1.0.0+1
environment:
  sdk: ">=2.17.6 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations: # Add this line
    sdk: flutter # Add this line
  intl: ^0.17.0 # Add this line
  cupertino_icons: ^1.0.2
  provider: ^6.0.3
  font_awesome_flutter: ^10.1.0
  dio: ^4.0.6
  socket_io_client: ^2.0.0
  json_annotation: ^4.4.0
  hmssdk_flutter: ^0.7.5
  image_picker: ^0.8.5+3
  shared_preferences: ^2.0.14
  firebase_messaging: ^13.0.0
  flutter_local_notifications: ^9.9.1
dev_dependencies:
  build_runner: ^2.0.0
  json_serializable: ^6.3.1
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
flutter:
  generate: true # Add this line
  uses-material-design: true
flutter_intl:
  enabled: true
