// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCqG38FbGM5mtVKvZhfQb1OoxpaVyJXVwI',
    appId: '1:285234451242:web:fca779619d95aa0d088453',
    messagingSenderId: '285234451242',
    projectId: 'flutter-example-b2c45',
    authDomain: 'flutter-example-b2c45.firebaseapp.com',
    storageBucket: 'flutter-example-b2c45.appspot.com',
    measurementId: 'G-89CNWF6TXZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD7IfeDfTrm39dwCUGQ7VsJ8EqEz5te030',
    appId: '1:285234451242:android:3bfe9fff873d1f53088453',
    messagingSenderId: '285234451242',
    projectId: 'flutter-example-b2c45',
    storageBucket: 'flutter-example-b2c45.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBmeEjjcckl35IPSak-jmIZafOGUgsTU2E',
    appId: '1:285234451242:ios:6c89537155f1ee21088453',
    messagingSenderId: '285234451242',
    projectId: 'flutter-example-b2c45',
    storageBucket: 'flutter-example-b2c45.appspot.com',
    iosClientId: '285234451242-bhb464scdj3q9ngisa1ttje8l0a1hp4l.apps.googleusercontent.com',
    iosBundleId: 'com.example.exampleFlutter11',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBmeEjjcckl35IPSak-jmIZafOGUgsTU2E',
    appId: '1:285234451242:ios:4ed7f6f17261ea9d088453',
    messagingSenderId: '285234451242',
    projectId: 'flutter-example-b2c45',
    storageBucket: 'flutter-example-b2c45.appspot.com',
    iosClientId: '285234451242-eaufero8r16sfo6ihbhnppodchh4a8af.apps.googleusercontent.com',
    iosBundleId: 'com.example.exampleFlutter',
  );
}
